### ISSUE TITLE
Not a issue - just to thank you and ask for your help

### ISSUE THREAD

**Issue by srlopez** [BaranMichal25/my_quotes#2]
Hi, Michal.
I'm sorry for daring to write here, but I don't know how to send you an email. So this way seems right to me.

I can sense that behind your application hides a very good example of architecture, but I am not able, yet, to discover it. You use Provider in an original way, block that invokes UseCases, but I do not see Uses Casepara to add authors or quotes.

Could you tell me which articles to read to better understand your architecture? Or even better, write a post about it.
Thanks in advance

**Comment by PawlikMichal25** [comment]
Hello!

**UseCases**
UseCases are totally optional and I added them where I felt they would be useful or consistent in some sense.
A good example is [SearchUseCase](https://github.com/BaranMichal25/my_quotes/blob/master/lib/domain/search_use_case.dart) - I think the code here didn't belong to Repositories (data layer) and I also didn't want to place it in [QuotesTabBloc](https://github.com/BaranMichal25/my_quotes/blob/c1230b24230d39bd619806350edeb874a13ae9b0/lib/tabs/quotes/quotes_tab_bloc.dart) because the bloc could potentially grow too big, when more features are added.
In my opinion, QuotesTabBloc is very readable right now, especially if you think how it would look if all the code from GetQuotesUseCase and SearchUseCase would live there.

But again, maybe this screen and bloc wouldn't actually grow, so it would be alright. 

**Architecture**
I'm actually planning to move away from Bloc in this project - it's my next step after refactoring SQFlite to Hive. I will be using ChangeNotifier with some tweaks.
You can read more about here:
https://flutter.dev/docs/development/data-and-backend/state-mgmt/simple
or before that: https://flutter.dev/docs/development/data-and-backend/state-mgmt/simple

Regarding the Provider, I created this project long ago and there are things which I will need to improve in a direction about which you can read in above-mentioned articles :)

**Comment by srlopez** [comment]
Thank you very much, again.
Waiting for your next refactoring.
